return {
  {
    prefix = 'clg',
    body = 'console.log($0)',
    desc = 'Displays a message in the console',
  },
  {
    prefix = 'cer',
    body = 'console.error($0)',
    desc = 'Displays a message in the console and also includes a stack trace from where the method was called',
  },
  {
    prefix = 'cwa',
    body = 'console.warn($0)',
    desc = 'Displays a message in the console but also displays a yellow warning icon along with the logged message',
  },
  {
    prefix = 'cin',
    body = 'console.info($0)',
    desc = 'Displays a message in the console but also displays a blue information icon along with the logged message',
  },
  {
    prefix = 'ctl',
    body = 'console.table($0)',
    desc = 'Logs table to console',
  },
  { prefix = 'fn', body = 'function $1($2) {\n\t$0\n}', desc = 'Function' },
  {
    prefix = 'nfn',
    body = 'const $1 = ($2) => {\n\t$0\n}',
    desc = 'Creates a named function',
  },
  {
    prefix = 'afr',
    body = 'const $1 = ($2) => $0',
    desc = 'Arrow function (return)',
  },
  {
    prefix = 'afn',
    body = 'async function $1($2) {\n\t$0\n}',
    desc = 'Async function',
  },
  {
    prefix = 'aaf',
    body = 'const $1 = async ($2) => {\n\t$0\n}',
    desc = 'Async arrow function',
  },
  {
    prefix = 'if',
    body = 'if ($1) {\n\t$0\n}',
    desc = 'If statement',
  },
  { prefix = 'ife', body = 'if ($1) {\n\t$2\n} else {\n\t$0\n}', desc = 'If else' },
  { prefix = 'ter', body = '$1 ? $2 : $0', desc = 'Ternary' },
  { prefix = 'try', body = 'try {\n\t$1\n} catch (error) {\n\t$0\n}', desc = 'Try catch' },
  {
    prefix = 'tryf',
    body = 'try {\n\t$1\n} catch (error) {\n\t$2\n} finally {\n\t$0\n}',
    desc = 'Try catch finally',
  },
  { prefix = 'fori', body = 'for (let i = 0; i < $1; i++) {\n\t$0\n}', desc = 'For loop' },
  { prefix = 'fof', body = 'for (const $1 of $2) {\n\t$0\n}', desc = 'Iterating over property names of iterable objects' },
  { prefix = 'fin', body = 'for (const $1 in $2) {\n\t$0\n}', desc = 'Iterating over property values of iterable objects' },
  { prefix = 'fre', body = '$1.forEach(($2) => {\n\t$0\n})', desc = 'Creates a forEach statement' },
  { prefix = 'map', body = '$1.map(($2) => $0)', desc = 'map' },
  { prefix = 'filter', body = '$1.filter(($2) => $0)', desc = 'filter' },
  { prefix = 'reduce', body = '$1.reduce((acc, $2) => $0, $3)', desc = 'reduce' },
  { prefix = 'find', body = '$1.find(($2) => $0)', desc = 'find' },
  {
    prefix = 'dob',
    body = 'const { $0 } = $1',
    desc = 'Creates and assigns a local variable using object destructing',
  },
  {
    prefix = 'dar',
    body = 'const [$0] = $1',
    desc = 'Creates and assigns a local variable using array destructing',
  },
  {
    prefix = 'imp',
    body = "import $0 from '$1'",
    desc = 'Import default',
  },
  { prefix = 'prom', body = 'new Promise((resolve, reject) => {\n\t$0\n})', desc = 'Creates and returns a new Promise in the standard ES7 syntax' },
  { prefix = 'then', body = '.then(($1) => $0)', desc = 'then' },
  { prefix = 'catch', body = '.catch((error) => $0)', desc = 'catch' },
  { prefix = 'ob', body = 'const $1 = {\n\t$0\n}', desc = 'Object' },
  { prefix = 'ar', body = 'const $1 = [$0]', desc = 'Array' },
  {
    prefix = 'sto',
    body = 'setTimeout(() => {\n\t$0\n}, $1)',
    desc = 'Executes the given function after the specified delay',
  },
  {
    prefix = 'sti',
    body = 'setInterval(() => {\n\t$0\n}, $1)',
    desc = 'Executes the given function at specified intervals',
  },
  {
    prefix = 'afrom',
    body = 'Array.from($1, ($2) => $0)',
    desc = 'Array.from',
  },
}
