require('configs.nvimTree')
require('configs.treesitter')
require('configs.autoPairs')
-- require('configs.luaLine')
require('configs.bufferLine')
require('configs.nvimComments')
-- require('configs.blankLine')
require('configs.hopNvim')
require('configs.telescope')
require('configs.gitSigns')
require('configs.dashboard')
require('configs.cmpConfig')
require('configs.lspConfig')
require("configs.toggleterm")
require('configs.folds')
