vim.g.mapleader = " "

vim.o.number = true
vim.o.relativenumber = true
vim.o.wrap = false
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.clipboard = "unnamedplus"
vim.o.undofile = true
vim.o.swapfile = false
vim.o.backup = false
vim.o.cursorline = true
vim.o.termguicolors = true
vim.o.scrolloff = 8
vim.o.sidescrolloff = 8
vim.o.hlsearch = true
vim.o.showcmd = false
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.mouse = "nvc"
vim.colorcolumn = "100"
vim.o.smoothscroll = true
vim.o.splitkeep = "screen"
vim.o.jumpoptions = "view"
vim.o.inccommand = "split"
vim.o.updatetime = 250
vim.o.timeoutlen = 300
vim.o.confirm = true
vim.o.virtualedit = "block"
vim.o.exrc = true
vim.o.signcolumn = "yes"

-- Fold
vim.o.foldcolumn = "0" -- Hide fold icons
vim.o.foldlevel = 99
vim.o.foldlevelstart = 99
vim.o.foldenable = false
vim.o.foldmethod = "expr"
vim.o.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.o.fillchars = [[eob: ,fold: ,foldopen: ,foldsep: ,foldclose: ]] 
